# This workflow will do a clean install of dependencies, build the source code, set up the firebase environement variables, and deploy

name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install -g firebase-tools && cd ./functions && npm ci

      - name: Build
        run: cd ./functions && npm run build

      - name: Set Up Config
        run: npm run firebase:setConfig bb.buzzernumber="$BUZZER_NUMBER" bb.twilioaccountsid="$TWILIO_ACCOUNT_SID" bb.twilioauthtoken="$TWILIO_AUTH_TOKEN" bb.twilionumber="$TWILIO_NUMBER" bb.url="$URL"
        env:
          BUZZER_NUMBER: ${{ secrets.BUZZER_NUMBER }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN}}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
          URL: ${{ secrets.URL }}

      - name: Deploy
        run: npm run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN}}
