# This workflow will do a clean install of node dependencies run tests

name: Test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: cd ./functions && npm ci

      - name: Lint
        run: cd ./functions && npm run lint
